### PR TITLE
remove interval send updateStatus

### PR DESCRIPTION
**Pull request by linus2code**
1. remove interval updateStatus notify
2. add currentTurnText for checking whois turn clearly

### CODE REVIEW

**Comment by norkator** [comment]
@linus2code can I review this or is there more commits coming?

**Comment by linus2code** [comment]
Yes, there is no more commits. And I made a react client for this backend. You can find the react one at here(https://github.com/linus2code/poker-pocket-react-client). I try to keep the same behavior and improve some.

**Comment by norkator** [comment]
> Yes, there is no more commits. And I made a react client for this backend. You can find the react one at here(https://github.com/linus2code/poker-pocket-react-client). I try to keep the same behavior and improve some.

Can I add this react version link to this backend readme?

**Review by norkator — APPROVED** [review]
Approved

**Comment by linus2code** [comment]
> > Yes, there is no more commits. And I made a react client for this backend. You can find the react one at here(https://github.com/linus2code/poker-pocket-react-client). I try to keep the same behavior and improve some.
> 
> Can I add this react version link to this backend readme?

Yes. i'm glad to hear that.

**Pull request merged**
